name: Run test

on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13, 3.14, 3.14t]
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --all-groups
      - name: Run Ruff linting
        run: uv run ruff check .
      - name: Run type check
        run: uv run zuban check
      - name: Run tests
        run: uv run pytest tests

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@master
      - uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay
      - name: Accept host key
        run: ssh-keyscan -H provinces.open-api.vn >> ~/.ssh/known_hosts
      - name: Run Ansible playbook
        run: ansible-playbook -i Deployment/Ansible/inventory.yml Deployment/Ansible/playbook.yml
